### ISSUE TITLE
Payment issue 'Het formulier is verlopen, probeer het opnieuw'

### ISSUE THREAD

**Issue by nuphoff** [DxEx/commerce_mollie#6]
I'm using this drupal module for an e-commerce website and when i'm redirected to Mollie for a payment i immediately receive an error in the form "Het formulier is verlopen, probeer het opnieuw." but you can still make a payment.

![afbeelding](https://user-images.githubusercontent.com/4758951/46338790-6bdad200-c631-11e8-949d-bdbc5e4276ad.png)

I've contacted Mollie and they said the following 'This is caused because you're doing a POST request instead of a GET request to Mollie'.
I used Fiddler to verify this and indeed a POST request is send with in the body information about return urls.

I've checked the mollie payment api and they have the following note:
`
You should use HTTP GET for the redirect to the _links.checkout URL. Using HTTP POST for redirection will cause issues with some payment methods or iDEAL issuers. Use HTTP status code 303 See Other to force an HTTP GET redirect.
`
Step 2 on https://docs.mollie.com/payments/overview

**Comment by nuphoff** [comment]
I've fixed the issue by making a change to line 33 in the file:
MolliePaymentOffsiteForm.php

from:
```
return $this->buildRedirectForm($form, $form_state, $mollie_payment->getPaymentUrl(), $data, 'post');
```

to:
```
return $this->buildRedirectForm($form, $form_state, $mollie_payment->getPaymentUrl(), $data, 'get');
```
should i create a PR for this?

**Comment by ndf** [comment]
Thanks nuphoff,

Yes please create a pull-request!

Can you also cross-post this issue on drupal.org ? 
There you can just copy-paste the information you typed here and add a link to the PR here.

I never got the "Het formulier is verlopen, probeer het opnieuw" error.
Do you know what triggers this? For example has the mollie-api or drupal-commerce api changed that tiggers this?
Do you foresee any risks or side-effects when we commit this change?

**Comment by ndf** [comment]
We fixed this one on drupal.org nuphoff
